stages:
  preprocess:
    cmd: conda run -n rf-detr python src/preprocess_pipeline.py
    deps:
      - src/preprocess_pipeline.py
      - src/preprocess_stage/resizer.py
      - src/preprocess_stage/tile_creator.py
      - src/preprocess_stage/splitter.py
      - src/preprocess_stage/augmenter.py
      - data/${task-name}/_annotations.coco.json
    params:
      - task-name
      - model-type
      - seed
      - preprocess
    outs:
      - data/${task-name}_formatted:
          cache: false

  train:
    cmd: conda run -n rf-detr python src/train.py
    deps:
      - src/train.py
      - data/${task-name}_formatted
      - params.yaml
    params:
      - train
      - task-name
      - model-type
      - seed
    outs:
      - trainings/${task-name}:
          cache: false

  process_results:
    cmd: conda run -n rf-detr python src/process_results.py
    deps:
      - src/process_results.py
      - trainings/${task-name}/log.txt
    params:
      - task-name
    outs:
      - trainings/temp/dvc_plots.json:
          cache: false
      - trainings/temp/dvc_metrics.json:
          cache: false

  test:
    cmd: conda run -n rf-detr python src/test.py
    deps:
      - src/test.py
      - trainings/${task-name}
      - data/temp/category_map.json
      - trainings/temp/run_info.json
    params:
      - task-name
      - train.project

metrics:
  - trainings/temp/dvc_metrics.json

plots:
  - Losses:
      x: epoch
      y:
        trainings/temp/dvc_plots.json:
          - train_loss
          - test_loss
          - ema_test_loss
  - mAP:
      x: epoch
      y:
        trainings/temp/dvc_plots.json:
          - map50
          - map50_95
          - ema_map50
          - ema_map50_95
  - Precision_Recall_F1:
      x: epoch
      y:
        trainings/temp/dvc_plots.json:
          - precision
          - recall
          - f1
          - ema_f1
          - ema_precision
          - ema_recall