stages:
  preprocess:
    cmd: conda run -n web2 python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/${task-name}/train/_annotations.coco.json
      - params.yaml
    outs:
      - data/${task-name}/category_map.json

  train:
    cmd: conda run -n web2 python src/train.py
    deps:
      - src/train.py
      - data/${task-name}
      - params.yaml
    params:
      - train
      - model
    outs:
      - trainings/${task-name}: # Carpeta de salida
          cache: true
      - run_info.json # Guardamos aquÃ­ el ID del run, no en params.yaml

  test:
    cmd: conda run -n web2 python src/test.py
    deps:
      - src/test.py
      - trainings/${task-name}
      - data/${task-name}/category_map.json
      - trainings/${task-name}/run_info.json
    params:
      - task-name