stages:
  wandb-login:
    cmd: wandb login
  preprocess:
    cmd: conda run -n rf-detr python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/${task-name}/train/_annotations.coco.json
      - params.yaml
    outs:
      - data/${task-name}/category_map.json

  train:
    cmd: conda run -n rf-detr python src/train.py
    deps:
      - src/train.py
      - data/${task-name}
      - params.yaml
    params:
      - train
      - model-type
    outs:
      - trainings/${task-name}:  # Carpeta de salida
          cache: true
      # - trainings/${task-name}/run_info.json
      # - trainings/${task-name}/results.json

  test:
    cmd: conda run -n rf-detr python src/test.py
    deps:
      - src/test.py
      - trainings/${task-name}
      - data/${task-name}/category_map.json
      - trainings/${task-name}/run_info.json
    params:
      - task-name