task-name: prueba_rfdetr
model-type: large
seed: 42

data-src1: E:\Images for labelling\Top  # Dataset local
data-src2: E:\slave_datasets\formatted_033  # Dataset remoto

preprocess:
  requires-preprocess: true
  saving-prob: 0.01  # Probabilidad de que se guarde una imagen aunque no tenga ninguna anotación
  resize: 0.33
  apply-roi: false
  train-ratio: 0.7
  test-ratio: 0.15
  val-ratio: 0.15
  augmentations-per-image: 2
  max-transforms-per-sample: 5

train:
  lr: 0.0001
  lr_encoder: 0.00015
  batch_size: 8
  grad_accum_steps: 4
  epochs: 30
  weight_decay: 1e-4
  tensorboard: false
  wandb: true
  project: top
  mlflow: false
  clearml: false
  run_test: true
  eval_max_dets: 500
