task-name: prueba_ps
model-type: nano
seed: 42

data-src1: C:\Users\u.etxeberria\Desktop\datasets\formatted\People - copia  # Dataset local
data-src2: C:\Users\u.etxeberria\Desktop\datasets\formatted\Box detection - copia  # Dataset remoto

preprocess:
  requires-preprocess: false
  saving-prob: 0.01  # Probabilidad de que se guarde una imagen aunque no tenga ninguna anotación
  resize: 1.0
  apply-roi: false
  train-ratio: 0.7
  test-ratio: 0.15
  val-ratio: 0.15
  augmentations-per-image: 2
  max-transforms-per-sample: 5

train:
  lr: 0.0001
  lr_encoder: 0.00015
  batch_size: 8
  grad_accum_steps: 3
  epochs: 3
  weight_decay: 1e-4
  tensorboard: false
  wandb: true
  project: prueba_ps
  mlflow: false
  clearml: false
  run_test: true
  eval_max_dets: 500
